module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: '#5B44E9',
        cabiza_blue: '#24BAD4',
        cabiza_blue_secondary: '#4CCBE1',
        yellow: '#FCCA03',
        cabiza_secondary: '#02BDDC',
        cabiza_secondary_tertiary: '#E5F7FB',
        secondary_light: '#BF85EA',
        cabiza_grey: '#828080',
        tertiary: '#5B188B',
        cabiza_tertiary: '#0294AC',
        grey_20: '#333333',
        grey_40: '#666666',
        grey_60: '#9A9A98',
        grey_80: '#CCCCCC',
        grey_85: '#D9D9D9',
        grey_95: '#F2F2F2',
        grey_98: '#FAFAFA',
        grey: '#D9D9D9',
        dark_: '#220934',
        dark_pri: '#013D47',
        cabiza_red: '#D12424',
        pink: '#FEF4CD',
        
        //New colors
        lighter: '#BFB6F6',
        primary_brand_lightest: '#EFEDFD',
        primary_brand_light: '#8E7FF0',
        secondary: '#404446',
        secondary_sky_dark: '#979C9E',
        secondary_brand_light: '#6C7072',
        secondary_ink_lighter: '#72777A',
        secondary_52: '#912CDB',
        secondary_sky_base: '#CDCFD0',
        secondary_sky_lighter: '#F2F4F5',
        secondary_ink_dark: '#303437',
        secondary_ink_darkest: '#090A0A',
        dark: '#040212',
        sky_light: '#E3E5E5',
        white: '#ffffff',
        footer: '#090425',
      },
    },
  },
  plugins: [],
};
